Lw cli api update
OmicsDataAutomation/OmicsDS pull request #39
Opened 2022-08-22 22:46 UTC by webberlh

Updates the query CLI to use the OmicsDS API to better conform to how the bindings works. Also adds the ability to export matrix files from feature-level arrays.

2022-08-24 21:05 UTC, webberlh commented
Currently, the decoding "cache" is just saving the last decoded GTF ID. The `deque` approach was about the same performance but the code was more complicated so I went with this approach, but we have the option of going back to a `deque` if needed without suffering much performance loss. Using some sort of caching approach beats out re-calculating, but this is fairly close as well so dropping it entirely is another option if we need to. 

I've left the sample map as a map for now, we can revisit this as we think about scaling.

Running the full query over our 14K dataset takes about 6 minutes with these changes.

2022-08-24 23:32 UTC, nalinigans requested changes
Looks good. Just wondering if we can move the inverse sample map to files supporting query/export functions.

2022-08-24 23:32 UTC, nalinigans commented on src/main/cpp/loader/omicsds_loader.cc
> +std::shared_ptr<std::unordered_map<size_t, std::string>> SampleMap::invert_sample_map(
Is this meant to be used by the cli/exporter process? Maybe we should move this to omicsds_export.cc.

2022-08-24 23:32 UTC, nalinigans commented on src/main/cpp/loader/omicsds_loader.cc
> +  auto sample_map_iter = map.begin();
Not necessary to do this right now. But, the inverse map will only be needed for the sample range that we are looking at. May not need to build it for all samples. May help with lookup performance.

2022-08-25 00:07 UTC, webberlh commented on src/main/cpp/loader/omicsds_loader.cc
> +  auto sample_map_iter = map.begin();
Good point, I've opened #40 to track this optimization.

2022-08-25 00:13 UTC, webberlh commented on src/main/cpp/loader/omicsds_loader.cc
> +std::shared_ptr<std::unordered_map<size_t, std::string>> SampleMap::invert_sample_map(
Primarily the export process will be interested in this. I implemented it here as a member function rather than a standalone function in `omicsds_export.cc` as it saved adding 3 functions to the public API of `SampleMap` (namely `begin()`, `end()`, and `erase()`). What are your thoughts on splitting the `SampleMap` class out into it's own file in the `utils` directory? Then both the loader and exporter could just include from there, and we avoid this issue of having exporter related code in the loader file.

2022-08-25 17:00 UTC, nalinigans commented on src/main/cpp/loader/omicsds_loader.cc
> +std::shared_ptr<std::unordered_map<size_t, std::string>> SampleMap::invert_sample_map(
Refactoring the `SampleMap` class into utils will be great. Please go ahead. Thanks.

2022-08-28 21:28 UTC, webberlh commented on src/main/cpp/loader/omicsds_loader.cc
> +std::shared_ptr<std::unordered_map<size_t, std::string>> SampleMap::invert_sample_map(
Refactor is now done. The `SampleMap` class has been moved to it's own file in `utils`. It also required the `split` function which was defined in `omicsds_loader.cc`, so I've moved that definition to `omicsds_file_utils.cc` for now. The CLI tests have also be refactored into the `tools` directory, and the build has been made conditional to avoid the linker issues we were experiencing.

2022-08-29 03:45 UTC, nalinigans approved these changes
Looks good to me. We probably need to file a defect with cmake for the inflateEnd zlib issue.

2022-08-29 15:09 UTC, merged