Lw configure step
OmicsDataAutomation/OmicsDS pull request #46
Opened 2022-09-23 20:28 UTC by webberlh

Adds the ability to pre-configure an OmicsDS workspace for import. This motivates the following changes which are roughly ordered to match how I've organized the commit history:

- Add protobuf message for import configuration.
- Enable protobuf messages handled by OmicsDS to either be written to disk as either the default byte format, or in JSON format.
- Move workspace initialization to location shared by loader, exporter, and configurer to allow for importing into an existing OmicsDS workspace.
- Expose new `OmicsModule` derived configurer responsible for mediating the configuration of the workspace.
- Add function for retrieving an `OmicsLoader` derived class that is able to make use of the workspace configuration.
- Add a new configure step to the CLI, and update the import step to pull in configuration information.

As an example, the following usage of the CLI is now supported:
```bash
omicsds configure -w workspace -f -l small_matrix_list -s small_map
omicsds import -w workspace -a array_sorted
omicsds import -w workspace -a array_unsorted -l small_matrix_sorted_list
```

2022-09-26 14:50 UTC, nalinigans requested changes
Very nice refactoring of some overdue old code! The configure step will evolve as we go along. But let's use this PR as a starting point to start this evolution discussion.

2022-09-26 14:50 UTC, nalinigans commented on src/main/cpp/loader/omicsds_loader.cc
> +  CHECK_RC(tiledb_array_create(m_tiledb_ctx, &array_schema));
Thanks for using `m_tiledb_ctx` and moving the initialization out of the member methods!

2022-09-26 14:50 UTC, nalinigans commented on src/main/cpp/utils/omicsds_import_config.h
> +  void merge(const OmicsDSImportConfig& update_config);
There is only one OmicsDSImportConfig instance supplied as input to merge. Can you update the doc with exactly what this function doing? Going forward, after we finish the first round of refactoring, we should probably use doxygen to generate api docs.

2022-09-26 14:50 UTC, nalinigans commented on tools/main/configure.cc
> +}
Saying that `configure can also take all command line arguments that can be provided to import` is a bit confusing. We probably should only use a configured json file as input to import apart from the actual bed/matris/sam files. Let's discuss this at some point. I am OK pulling this in for now.

2022-09-26 17:13 UTC, webberlh commented on src/main/cpp/utils/omicsds_import_config.h
> +  void merge(const OmicsDSImportConfig& update_config);
Done! Originally, this was a function rather than a method so there were explicitly two instances in the signature. I've clarified that point and added a few more details to the docstring.

2022-09-26 17:20 UTC, webberlh commented on tools/main/configure.cc
> +}
Sounds good, at the moment configuration is done at the workspace level whereas if we go down the route of only allowing json configuration we may need to consider making it array level since having to edit a file for every import may be detrimental to user experience. Then again maybe I'm overestimating how often you'd want to vary anything besides the file list. I'll think on this some more.

2022-09-27 14:14 UTC, nalinigans approved these changes
Looks good

2022-09-27 19:26 UTC, merged